// Schema: which fields (and what type) each template exposes in the TweaksPanel.
// type: 'text' | 'textarea' | 'color' | 'image'
// key must match a key in MIDOK_CONTENT or a token key.

export const SHARED_SCHEMA = [
  { key: 'contact', label: 'Kontakt / URL', type: 'text' },
  { key: 'pillar1', label: 'Säule 1 Titel', type: 'text' },
  { key: 'pillar2', label: 'Säule 2 Titel', type: 'text' },
  { key: 'pillar3', label: 'Säule 3 Titel', type: 'text' },
];

export const SCHEMA = {
  // ─── V1T1 / V2T1 — Hero Team ───
  v1t1: [
    { key: 't1_headline_a', label: 'Headline A', type: 'text' },
    { key: 't1_headline_b', label: 'Headline B', type: 'text' },
    { key: 't1_sub', label: 'Subtext', type: 'textarea' },
    { key: 't1_name', label: 'Name', type: 'text' },
    { key: 't1_role', label: 'Rolle', type: 'text' },
    { key: 't1_tenure', label: 'Dauer', type: 'text' },
    { key: 't1_stat1_n', label: 'Stat 1 Zahl', type: 'text' },
    { key: 't1_stat1_l', label: 'Stat 1 Label', type: 'text' },
    { key: 't1_stat2_n', label: 'Stat 2 Zahl', type: 'text' },
    { key: 't1_stat2_l', label: 'Stat 2 Label', type: 'text' },
    { key: 't1_stat3_n', label: 'Stat 3 Zahl', type: 'text' },
    { key: 't1_stat3_l', label: 'Stat 3 Label', type: 'text' },
    { key: 't1_stat4_n', label: 'Stat 4 Zahl', type: 'text' },
    { key: 't1_stat4_l', label: 'Stat 4 Label', type: 'text' },
    { key: 'img_hero', label: 'Bild: Porträt', type: 'image' },
  ],
  v2t1: [
    { key: 't1_headline_a', label: 'Headline A', type: 'text' },
    { key: 't1_headline_b', label: 'Headline B', type: 'text' },
    { key: 't1_sub', label: 'Subtext', type: 'textarea' },
    { key: 't1_name', label: 'Name', type: 'text' },
    { key: 't1_role', label: 'Rolle', type: 'text' },
    { key: 't1_tenure', label: 'Dauer', type: 'text' },
    { key: 't1_stat1_n', label: 'Stat 1 Zahl', type: 'text' },
    { key: 't1_stat1_l', label: 'Stat 1 Label', type: 'text' },
    { key: 't1_stat2_n', label: 'Stat 2 Zahl', type: 'text' },
    { key: 't1_stat2_l', label: 'Stat 2 Label', type: 'text' },
    { key: 't1_stat3_n', label: 'Stat 3 Zahl', type: 'text' },
    { key: 't1_stat3_l', label: 'Stat 3 Label', type: 'text' },
    { key: 't1_stat4_n', label: 'Stat 4 Zahl', type: 'text' },
    { key: 't1_stat4_l', label: 'Stat 4 Label', type: 'text' },
    { key: 'img_hero', label: 'Bild: Porträt', type: 'image' },
  ],

  // ─── V1T2 / V2T2 — Team Ensemble ───
  v1t2: [
    { key: 't2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 't2_meta', label: 'Meta', type: 'text' },
    { key: 't2_headline_a', label: 'Headline A', type: 'text' },
    { key: 't2_headline_b', label: 'Headline B', type: 'text' },
    { key: 't2_sub', label: 'Subtext', type: 'textarea' },
    { key: 't2_portrait_name', label: 'Porträt Name', type: 'text' },
    { key: 't2_portrait_role', label: 'Porträt Rolle', type: 'text' },
    { key: 't2_portrait_quote', label: 'Zitat', type: 'textarea' },
    { key: 'img_portrait', label: 'Bild: Porträt', type: 'image' },
    { key: 'img_p1', label: 'Bild: Person 1', type: 'image' },
    { key: 'img_p2', label: 'Bild: Person 2', type: 'image' },
    { key: 'img_p3', label: 'Bild: Person 3', type: 'image' },
    { key: 'img_p4', label: 'Bild: Person 4', type: 'image' },
    { key: 'img_p5', label: 'Bild: Person 5', type: 'image' },
    { key: 'img_p6', label: 'Bild: Person 6', type: 'image' },
  ],
  v2t2: [
    { key: 't2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 't2_meta', label: 'Meta', type: 'text' },
    { key: 't2_headline_a', label: 'Headline A', type: 'text' },
    { key: 't2_headline_b', label: 'Headline B', type: 'text' },
    { key: 't2_sub', label: 'Subtext', type: 'textarea' },
    { key: 't2_portrait_name', label: 'Porträt Name', type: 'text' },
    { key: 't2_portrait_role', label: 'Porträt Rolle', type: 'text' },
    { key: 't2_portrait_quote', label: 'Zitat', type: 'textarea' },
    { key: 'img_portrait', label: 'Bild: Porträt', type: 'image' },
    { key: 'img_p1', label: 'Bild: Person 1', type: 'image' },
    { key: 'img_p2', label: 'Bild: Person 2', type: 'image' },
    { key: 'img_p3', label: 'Bild: Person 3', type: 'image' },
    { key: 'img_p4', label: 'Bild: Person 4', type: 'image' },
    { key: 'img_p5', label: 'Bild: Person 5', type: 'image' },
    { key: 'img_p6', label: 'Bild: Person 6', type: 'image' },
  ],

  // ─── V1T3 / V2T3 — Interview ───
  v1t3: [
    { key: 't3_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 't3_question', label: 'Frage', type: 'textarea' },
    { key: 't3_answer', label: 'Antwort', type: 'textarea' },
    { key: 't3_name', label: 'Name', type: 'text' },
    { key: 't3_role', label: 'Rolle', type: 'text' },
    { key: 't3_years', label: 'Jahre (Zahl)', type: 'text' },
    { key: 't3_yearsLabel', label: 'Jahre Label', type: 'text' },
    { key: 'img_interview', label: 'Bild: Porträt', type: 'image' },
  ],
  v2t3: [
    { key: 't3_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 't3_question', label: 'Frage', type: 'textarea' },
    { key: 't3_answer', label: 'Antwort', type: 'textarea' },
    { key: 't3_name', label: 'Name', type: 'text' },
    { key: 't3_role', label: 'Rolle', type: 'text' },
    { key: 't3_years', label: 'Jahre (Zahl)', type: 'text' },
    { key: 't3_yearsLabel', label: 'Jahre Label', type: 'text' },
    { key: 'img_interview', label: 'Bild: Porträt', type: 'image' },
  ],

  // ─── V1S1 / V2S1 — Fachbeitrag ───
  v1s1: [
    { key: 's1_meta', label: 'Meta', type: 'text' },
    { key: 's1_headline_a', label: 'Headline A', type: 'text' },
    { key: 's1_headline_b', label: 'Headline B', type: 'text' },
    { key: 's1_term', label: 'Fachbegriff', type: 'text' },
    { key: 's1_norm', label: 'Norm', type: 'text' },
    { key: 's1_def', label: 'Definition', type: 'textarea' },
    { key: 's1_step1', label: 'Schritt 1', type: 'text' },
    { key: 's1_step2', label: 'Schritt 2', type: 'text' },
    { key: 's1_step3', label: 'Schritt 3', type: 'text' },
    { key: 's1_step4', label: 'Schritt 4', type: 'text' },
    { key: 's1_step5', label: 'Schritt 5', type: 'text' },
    { key: 's1_footer', label: 'Footer', type: 'text' },
  ],
  v2s1: [
    { key: 's1_meta', label: 'Meta', type: 'text' },
    { key: 's1_headline_a', label: 'Headline A', type: 'text' },
    { key: 's1_headline_b', label: 'Headline B', type: 'text' },
    { key: 's1_term', label: 'Fachbegriff', type: 'text' },
    { key: 's1_norm', label: 'Norm', type: 'text' },
    { key: 's1_def', label: 'Definition', type: 'textarea' },
    { key: 's1_step1', label: 'Schritt 1', type: 'text' },
    { key: 's1_step2', label: 'Schritt 2', type: 'text' },
    { key: 's1_step3', label: 'Schritt 3', type: 'text' },
    { key: 's1_step4', label: 'Schritt 4', type: 'text' },
    { key: 's1_step5', label: 'Schritt 5', type: 'text' },
    { key: 's1_footer', label: 'Footer', type: 'text' },
  ],

  // ─── V1S2 / V2S2 — Countdown ───
  v1s2: [
    { key: 's2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 's2_headline_a', label: 'Headline A', type: 'text' },
    { key: 's2_headline_b', label: 'Headline B', type: 'text' },
    { key: 's2_headline_c', label: 'Headline C', type: 'text' },
    { key: 's2_dateA', label: 'Datum A', type: 'text' },
    { key: 's2_dateB', label: 'Datum B (Jahr)', type: 'text' },
    { key: 's2_sub_editorial', label: 'Subtext', type: 'textarea' },
    { key: 's2_countdown', label: 'Countdown Zahl', type: 'text' },
    { key: 's2_countdownL', label: 'Countdown Label', type: 'text' },
    { key: 's2_cta', label: 'CTA Text', type: 'textarea' },
  ],
  v2s2: [
    { key: 's2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 's2_headline_a', label: 'Headline A', type: 'text' },
    { key: 's2_headline_b', label: 'Headline B', type: 'text' },
    { key: 's2_headline_c', label: 'Headline C', type: 'text' },
    { key: 's2_dateA', label: 'Datum A', type: 'text' },
    { key: 's2_dateB', label: 'Datum B (Jahr)', type: 'text' },
    { key: 's2_sub_editorial', label: 'Subtext', type: 'textarea' },
    { key: 's2_countdown', label: 'Countdown Zahl', type: 'text' },
    { key: 's2_countdownL', label: 'Countdown Label', type: 'text' },
    { key: 's2_cta', label: 'CTA Text', type: 'textarea' },
  ],

  // ─── V1S3 / V2S3 — Karussell Cover ───
  v1s3: [
    { key: 's3_meta', label: 'Meta', type: 'text' },
    { key: 's3_line1', label: 'Zeile 1', type: 'text' },
    { key: 's3_line2', label: 'Zeile 2', type: 'text' },
    { key: 's3_sub', label: 'Subtext', type: 'textarea' },
    { key: 'img_machine', label: 'Bild: Maschine', type: 'image' },
  ],
  v2s3: [
    { key: 's3_meta', label: 'Meta', type: 'text' },
    { key: 's3_line1', label: 'Zeile 1', type: 'text' },
    { key: 's3_line2', label: 'Zeile 2', type: 'text' },
    { key: 's3_sub', label: 'Subtext', type: 'textarea' },
    { key: 'img_machine', label: 'Bild: Maschine', type: 'image' },
  ],

  // ─── V1B1 / V2B1 — Kunden-Logos ───
  v1b1: [
    { key: 'b1_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'b1_headline_a', label: 'Headline A', type: 'text' },
    { key: 'b1_headline_b', label: 'Headline B', type: 'text' },
    { key: 'b1_k1_n', label: 'Kunde 1 Name', type: 'text' },
    { key: 'b1_k1_s', label: 'Kunde 1 Branche', type: 'text' },
    { key: 'b1_k2_n', label: 'Kunde 2 Name', type: 'text' },
    { key: 'b1_k2_s', label: 'Kunde 2 Branche', type: 'text' },
    { key: 'b1_k3_n', label: 'Kunde 3 Name', type: 'text' },
    { key: 'b1_k3_s', label: 'Kunde 3 Branche', type: 'text' },
    { key: 'b1_k4_n', label: 'Kunde 4 Name', type: 'text' },
    { key: 'b1_k4_s', label: 'Kunde 4 Branche', type: 'text' },
    { key: 'b1_k5_n', label: 'Kunde 5 Name', type: 'text' },
    { key: 'b1_k5_s', label: 'Kunde 5 Branche', type: 'text' },
    { key: 'b1_k6_n', label: 'Kunde 6 Name', type: 'text' },
    { key: 'b1_k6_s', label: 'Kunde 6 Branche', type: 'text' },
    { key: 'img_logo1', label: 'Logo 1', type: 'image' },
    { key: 'img_logo2', label: 'Logo 2', type: 'image' },
    { key: 'img_logo3', label: 'Logo 3', type: 'image' },
    { key: 'img_logo4', label: 'Logo 4', type: 'image' },
    { key: 'img_logo5', label: 'Logo 5', type: 'image' },
    { key: 'img_logo6', label: 'Logo 6', type: 'image' },
  ],
  v2b1: [
    { key: 'b1_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'b1_headline_a', label: 'Headline A', type: 'text' },
    { key: 'b1_headline_b', label: 'Headline B', type: 'text' },
    { key: 'b1_k1_n', label: 'Kunde 1 Name', type: 'text' },
    { key: 'b1_k1_s', label: 'Kunde 1 Branche', type: 'text' },
    { key: 'b1_k2_n', label: 'Kunde 2 Name', type: 'text' },
    { key: 'b1_k2_s', label: 'Kunde 2 Branche', type: 'text' },
    { key: 'b1_k3_n', label: 'Kunde 3 Name', type: 'text' },
    { key: 'b1_k3_s', label: 'Kunde 3 Branche', type: 'text' },
    { key: 'b1_k4_n', label: 'Kunde 4 Name', type: 'text' },
    { key: 'b1_k4_s', label: 'Kunde 4 Branche', type: 'text' },
    { key: 'b1_k5_n', label: 'Kunde 5 Name', type: 'text' },
    { key: 'b1_k5_s', label: 'Kunde 5 Branche', type: 'text' },
    { key: 'b1_k6_n', label: 'Kunde 6 Name', type: 'text' },
    { key: 'b1_k6_s', label: 'Kunde 6 Branche', type: 'text' },
    { key: 'img_logo1', label: 'Logo 1', type: 'image' },
    { key: 'img_logo2', label: 'Logo 2', type: 'image' },
    { key: 'img_logo3', label: 'Logo 3', type: 'image' },
    { key: 'img_logo4', label: 'Logo 4', type: 'image' },
    { key: 'img_logo5', label: 'Logo 5', type: 'image' },
    { key: 'img_logo6', label: 'Logo 6', type: 'image' },
  ],

  // ─── V1B2 / V2B2 — Case Study ───
  v1b2: [
    { key: 'b2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'b2_caseNr', label: 'Case Nr.', type: 'text' },
    { key: 'b2_title', label: 'Projekttitel', type: 'text' },
    { key: 'b2_customer', label: 'Kunde', type: 'text' },
    { key: 'b2_body', label: 'Beschreibung', type: 'textarea' },
    { key: 'b2_k1_n', label: 'KPI 1 Zahl', type: 'text' },
    { key: 'b2_k1_l', label: 'KPI 1 Label', type: 'text' },
    { key: 'b2_k2_n', label: 'KPI 2 Zahl', type: 'text' },
    { key: 'b2_k2_l', label: 'KPI 2 Label', type: 'text' },
    { key: 'b2_k3_n', label: 'KPI 3 Zahl', type: 'text' },
    { key: 'b2_k3_l', label: 'KPI 3 Label', type: 'text' },
    { key: 'b2_k4_n', label: 'KPI 4 Zahl', type: 'text' },
    { key: 'b2_k4_l', label: 'KPI 4 Label', type: 'text' },
    { key: 'img_case', label: 'Bild: Projekt', type: 'image' },
  ],
  v2b2: [
    { key: 'b2_eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'b2_caseNr', label: 'Case Nr.', type: 'text' },
    { key: 'b2_title', label: 'Projekttitel', type: 'text' },
    { key: 'b2_customer', label: 'Kunde', type: 'text' },
    { key: 'b2_body', label: 'Beschreibung', type: 'textarea' },
    { key: 'b2_k1_n', label: 'KPI 1 Zahl', type: 'text' },
    { key: 'b2_k1_l', label: 'KPI 1 Label', type: 'text' },
    { key: 'b2_k2_n', label: 'KPI 2 Zahl', type: 'text' },
    { key: 'b2_k2_l', label: 'KPI 2 Label', type: 'text' },
    { key: 'b2_k3_n', label: 'KPI 3 Zahl', type: 'text' },
    { key: 'b2_k3_l', label: 'KPI 3 Label', type: 'text' },
    { key: 'b2_k4_n', label: 'KPI 4 Zahl', type: 'text' },
    { key: 'b2_k4_l', label: 'KPI 4 Label', type: 'text' },
    { key: 'img_case', label: 'Bild: Projekt', type: 'image' },
  ],

  // ─── V1B3 / V2B3 — Testimonial ───
  v1b3: [
    { key: 'b3_quote', label: 'Zitat', type: 'textarea' },
    { key: 'b3_name', label: 'Name', type: 'text' },
    { key: 'b3_role', label: 'Rolle', type: 'text' },
    { key: 'b3_logoChip', label: 'Logo Chip', type: 'text' },
    { key: 'b3_row1_label', label: 'Vergleich 1 Label', type: 'text' },
    { key: 'b3_row1_before', label: 'Vergleich 1 Vorher', type: 'text' },
    { key: 'b3_row1_after', label: 'Vergleich 1 Nachher', type: 'text' },
    { key: 'b3_row2_label', label: 'Vergleich 2 Label', type: 'text' },
    { key: 'b3_row2_before', label: 'Vergleich 2 Vorher', type: 'text' },
    { key: 'b3_row2_after', label: 'Vergleich 2 Nachher', type: 'text' },
    { key: 'b3_row3_label', label: 'Vergleich 3 Label', type: 'text' },
    { key: 'b3_row3_before', label: 'Vergleich 3 Vorher', type: 'text' },
    { key: 'b3_row3_after', label: 'Vergleich 3 Nachher', type: 'text' },
    { key: 'img_testimonial', label: 'Bild: Kunde', type: 'image' },
  ],
  v2b3: [
    { key: 'b3_quote', label: 'Zitat', type: 'textarea' },
    { key: 'b3_name', label: 'Name', type: 'text' },
    { key: 'b3_role', label: 'Rolle', type: 'text' },
    { key: 'b3_logoChip', label: 'Logo Chip', type: 'text' },
    { key: 'b3_row1_label', label: 'Vergleich 1 Label', type: 'text' },
    { key: 'b3_row1_before', label: 'Vergleich 1 Vorher', type: 'text' },
    { key: 'b3_row1_after', label: 'Vergleich 1 Nachher', type: 'text' },
    { key: 'b3_row2_label', label: 'Vergleich 2 Label', type: 'text' },
    { key: 'b3_row2_before', label: 'Vergleich 2 Vorher', type: 'text' },
    { key: 'b3_row2_after', label: 'Vergleich 2 Nachher', type: 'text' },
    { key: 'b3_row3_label', label: 'Vergleich 3 Label', type: 'text' },
    { key: 'b3_row3_before', label: 'Vergleich 3 Vorher', type: 'text' },
    { key: 'b3_row3_after', label: 'Vergleich 3 Nachher', type: 'text' },
    { key: 'img_testimonial', label: 'Bild: Kunde', type: 'image' },
  ],
};
